#!/bin/bash

mkdir /home/$USER/logs #used for storing user logs

cd /home/$USER/
mv /home/$USER/bash /home/$USER/bin
git clone https://github.com/zigjag/c_programs.git
git clone https://github.com/zigjag/python_programs.git
git clone https://github.com/zigjag/node.git
git clone https://github.com/zigjag/config.git
git clone https://github/zigjag/cv.git
git clone https://github/zigjag/node.git
git clone https://github/zigjag/electron.git
git clone https://github/zigjag/practice_python.git
git clone https://github/zigjag/GamesJS.git
git clone https://github/zigjag/AI_py.git
git clone https://github/zigjag/cpp_programs.git

mkdir /home/$USER/Github; cd /home/$USER/Github
git clone https://github.com/zigjag/Programmapedia.git
git clone https://github.com/zigjag/Wiki-API.git
git clone https://github.com/zigjag/budgetCrud.git
git clone https://github.com/zigjag/react.git
git clone https://github.com/zigjag/securitynode.git

bash /home/$USER/bin/configSetup
