#!/bin/bash

chmod +x /home/$USER/bin/* /home/$USER/python_programs/* /home/$USER/c_programs/*
sudo sed -i "1i\bash /home/$USER/bin/copyConfig" /etc/profile
sudo sed -i "1i\bash /home/$USER/bin/todo" /home/$USER/.bashrc
sudo sed -i "\$a PATH=$PATH:/home/$USER/bin:/home/$USER/c_programs:/home/$USER/python_programs; export PATH" /etc/bashrc
sudo cp /home/$USER/config/.hyper.js /home/$USER/; sudo cp /home/$USER/config/.bashrc /home/$USER/
sudo sed -i "\$a alias gpa='python /home/$USER/python_programs/gitPushAll.py'" /etc/bashrc
sudo sed -i "\$a alias gs='git status'" /etc/bashrc
echo '>>>>>>>>>>>>Config Setup is done<<<<<<<<<<<<<'
